### ISSUE TITLE
Completely breaks walking animation when using GoGo Loco

### ISSUE THREAD

**Issue by Eidenz** [Ess-Ka/EsskaAV3Obfuscator#1]
I use GoGo Loco on almost all my avatars. It's a sort of set of animations to allow you to do different poses when using desktop/3 point tracking.
It's free here: https://booth.pm/en/items/3290806

If I obfuscate my avatar with it, the walking animation completely breaks. The worse is that this is "permanent": removing obfuscation data does not recover the animation until  GoGo Loco is fully removed from the avatar.

I needed to re-import GoGo Loco (and remove the obfuscation tool?) to fix the issue.

This is a great tool, but quite sad if there is no way to use it along with the "animation pack".

**Comment by Ess-Ka** [comment]
Thank you for reporting and sorry for inconvenience. I will try to find out tomorrow, what is different with GoGo Loco. I will let you know, as soon I have a solution.

**Comment by Eidenz** [comment]
Thanks, I'd be glad to annoy rippers if this gets fixed x)

In the meantime, I'll try it on avatars without GoGo Loco

**Comment by Ess-Ka** [comment]
I figured out, what exactly happens. GoGo Loco uses BlendTrees, which are saved as external assets (GoGo Loco\Animations\BlendTree folder). AV3Obfuscator updates this BlendTrees, because it considers it as part of the current controller. I have to check, if the BlendTree is an exteral asset and I must copy it, like for other files too. You hear from me, as soon I have a new package.

In case of your broken animations - reimport the GoGo Loco package should fix this.

Remember, obfuscation is not encryption. I recommend to use AV3Obfuscator in combination with GTAvaCrypt. Then, your are more on the safe side ;-)

**Comment by Ess-Ka** [comment]
I remarked, that GoGo Loco has VRCParameterDrivers on StateMachines. I didn't handle that case and this is the main reason, why it broke in VRChat. I have fixed the issue and tested in VRChat. Looks good as far. Also, GoGo Loco BlendTrees will not anymore be overwritten. Please, give me feedback, if it works for you (see Release v1.01)

**Comment by Eidenz** [comment]
Very first test: the character is no longer sliding on the floor, but still not walking, rather switching between still animations.

I will be trying a couple more options, disabling some optional obfuscation (had everything on at first).

**Comment by Ess-Ka** [comment]
Yes, please - a video would help. Which type of controller you have choosed? I currently use "Go All Base 2.0 WD" with all obfuscation option "on" for testing.

**Comment by Eidenz** [comment]
I will record one when possible then.

I use "Go All Base 1.0", so without the write defaults.

**Comment by Eidenz** [comment]
So this is a short video before obfuscating, to use as a control: https://cloud.eidenz.com/f/6d5a3e4224cf48fd99ae/

and this is what happens after obfuscating: https://cloud.eidenz.com/f/71399bdf1a464ec1bf39/

**Comment by Eidenz** [comment]
Note: I just tried the "Go All Base 1.0 WD" to see if write defaults had anything to do with it, same issue.

**Comment by Ess-Ka** [comment]
Thank you! I can reproduce the behavior. VRChat uses proxy animations, which will be replaced in runtime. These proxy animations are only placeholders in the own animator. GoGo Loco has them referenced too. But I obfuscate these proxy animations, so VRC cannot replace the clips in runtime anymore. I have to exclude the proxy animation clips from obfuscation.

**Comment by Eidenz** [comment]
Oh okay I see, quite impressive how quick you are to locate the problem.

**Comment by Eidenz** [comment]
It worked! All good now with all obfuscation settings on. Thank you c:

**Comment by Ess-Ka** [comment]
Perfect! Have a nice day :-)
